### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Zemogiter** [FluffierThanThou/ResearchTree#53]
**Describe the bug**  
While compiling the source code for this mod (to start working on a 1.3 update) I get this error:
```
Delegate 'Action<Rect>' does not take 0 arguments
```
in `MainTabWindow.cs`
The only changes to the source code are the ones from #52 and updating Lib.Harmony and Multiplayer API.
**Expected behavior**  
Successfull compilation and the mod's dll files in output folder.
